using Section05.Class;
using Section05.Constructor;
using Section05.Properties;
using Section05.Methods;
using Section05.Parameters;
using Section05.Operator;
using Section05.Static;
using Section05.QuizApplication;

namespace Section05
{
    class Program
    {
        public static void Main(string[] args)
        {
            // 112. Creating first class
            // Bike bike = new Bike();
            // bike.Run();

            // 113. Custom constructore
            // Car def = new Car();
            // Car audi = new Car("Audi", "A7");
            // Car bmw = new Car("BMW", "i8");

            // def.Run();
            // audi.Run();
            // bmw.Run();

            // 114. Properties - autogenerated
            // Student s1 = new Student("John", 18);
            // Student s2 = new Student("Jane", 25);
            // Student s3 = new Student("Rob", 15);            

            // s2.Name = "Jane Doe"; // update object s2 Name using setter 
            // s3.Age = 19; // update object s3 Age using setter 

            // s1.PrintDetails();
            // s2.PrintDetails();
            // s3.PrintDetails();   

            // 117. Multiple constructors
            // Customer cstm1 = new Customer(); 
            // Customer cstm2 = new Customer("John");         
            // Customer cstm3 = new Customer("Bob", "LA", "123-45678");   

            // cstm2.City = "NY"; // use setters to update cstm2 City
            // cstm2.Mobile = "098-12345"; // use setters to update cstm2 Mobile
               
            // cstm1.GetDetails();     
            // cstm2.GetDetails();     
            // cstm3.GetDetails();  

            // 120. Methods in classes
            // User user = new User("John", "john@gmail.com", "password??");

            // user.Login("test", "test"); // login with invalid credentials
            // user.Login("john@gmail.com", "password??"); // login with valid credentials

            // Console.WriteLine();

            // user.UpdatePassword("test", "newPassword?"); // try to update password with invalid current password
            // user.UpdatePassword("password??", "newPassword?"); // update password

            // Console.WriteLine();

            // user.Login("john@gmail.com", "password??"); // login with old credentials
            // user.Login("john@gmail.com", "newPassword?"); // login with new credentials

            // 125. Optional parameters
            // Person p = new Person("John");

            // p.SayHello(); // call method without an argument
            // p.SayHello("Welcome"); // call method with an argument

            // 126. Named parameters
            // House h1 = new House("Colombo", "Sri Lanka");
            // House h2 = new House(city: "Malabe", country: "Sri Lanka");
            // House h3 = new House(country: "USA", city: "New York"); // order or arguments does not matter when using named parameters

            // h1.PrintAddress();
            // h2.PrintAddress();
            // h3.PrintAddress();

            // 127. Operator overloading
            // Point a = new Point(5, 10);
            // Point b = new Point(15, 20);

            // Point c = a + b; // use overload +

            // Console.WriteLine($"X: {c.X}, Y: {c.Y}");

            // 128: Passign arguments by value and by reference
            // int num = 10;

            // Increment.Increse(num);
            // Console.WriteLine($"num: {num}\n");

            // Increment.IncreaseByReference(ref num);
            // Console.WriteLine($"num: {num}\n");

            // 129: Computed properties
            // Rectangle r1 = new Rectangle(5, 5);
            // Rectangle r2 = new Rectangle(123, 13);

            // Console.WriteLine($"area of r1: {r1.GetArea()}");
            // Console.WriteLine($"area of r2: {r2.Area}");

            // 130. Static methods
            // ProgramUser.SetUser("John", "Password1");
            // ProgramUser.PrintUser();

            // ProgramUser.SetUser("Jane", "Password2");
            // ProgramUser.PrintUser();

            // 131. Static fields
            // Game g1 = new Game("Call of Duty", "Action");
            // Game g2 = new Game("Battlefield", "Action");
            // Game g3 = new Game("Silent Hill", "Horror");

            // Console.WriteLine($"Number of installed games: {Game.NumOfGames}\n"); // accessing the static field

            // Game g4 = new Game("Grid 2", "Racing");
            // Game g5 = new Game("GTA", "Online");

            // g1.PrintGame();
            // g2.PrintGame();
            // g3.PrintGame();
            // g4.PrintGame();
            // g5.PrintGame();
            // Console.WriteLine($"Number of installed games: {Game.NumOfGames}"); // accessing the static field

            // 136. Read only ptoperties
            // Book b1 = new Book("1984", "George Orwell");
            // Book b2 = new Book("To Kill a Mockingbird", "Harper Lee");
            // Book b3 = new Book("The Hobbit", "J.R.R. Tolkien");

            // b1.PrintDetails();
            // b2.PrintDetails();
            // b3.PrintDetails();

            // b1.UpdateAuthor("George Orwell++");
            // b2.UpdateBook("To Kill a Mockingbird", "Harper lee++");
            // b3.UpdateName("The Hobbit+");

            // b1.PrintDetails();
            // b2.PrintDetails();
            // b3.PrintDetails();

            // 137. Write only property
            // Admin admin = new Admin("john@gmail.com", "testpassword123?");

            // Console.WriteLine($"email: {admin.Email}");
            // Console.WriteLine($"password: {admin.Password}"); // not allowed because Password field is write only

            // 138. Const vs read only
            // Circle c1 = new Circle(7);
            // Circle c2 = new Circle(10);

            // Console.WriteLine($"area when r = 7cm: {c1.GetArea()}cm");
            // Console.WriteLine($"perimeter when r = 7cm: {c1.GetPerimeter()}cm");

            // Console.WriteLine($"area when r = 10cm: {c2.GetArea()}cm");
            // Console.WriteLine($"perimeter when r = 10cm: {c2.GetPerimeter()}cm");

            // 139: Quiz app
            QuizApp qa = new QuizApp();
            qa.StartGame();
        }
    }
}